# Generated by Django 5.1.3 on 2024-11-28 12:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_remove_provider_config_alter_provider_provider_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProxmoxProvider',
            fields=[
                ('provider_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.provider')),
                ('test_field', models.CharField(max_length=20)),
            ],
            bases=('core.provider',),
        ),
    ]
