# Generated by Django 5.1.3 on 2024-11-29 13:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_is_arhived_host_is_archived'),
        ('proxmox', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('provider_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.provider')),
                ('proxmox_host', models.CharField(max_length=20)),
                ('proxmox_user', models.CharField(max_length=20)),
                ('proxmox_password', models.CharField(max_length=20)),
            ],
            bases=('core.provider',),
        ),
        migrations.DeleteModel(
            name='ProxmoxProvider',
        ),
    ]
