# Generated by Django 5.1.3 on 2024-11-29 14:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proxmox', '0002_provider_delete_proxmoxprovider'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='provider',
            name='proxmox_password',
        ),
        migrations.AddField(
            model_name='provider',
            name='proxmox_token_name',
            field=models.CharField(max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='provider',
            name='proxmox_token_value',
            field=models.CharField(max_length=50),
            preserve_default=False,
        ),
    ]
