# Generated by Django 5.1.3 on 2024-11-29 14:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0005_remove_processor_config_instance_host_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InfluxdbProcessor',
            fields=[
                ('processor_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.processor')),
                ('url', models.CharField(max_length=256)),
                ('token', models.CharField(max_length=256)),
                ('org', models.CharField(max_length=256)),
                ('bucket', models.CharField(max_length=256)),
                ('verify_ssl', models.BooleanField(default=False)),
                ('timeout', models.IntegerField(default=10000)),
            ],
            bases=('core.processor',),
        ),
    ]
