# Generated by Django 5.1.3 on 2024-11-30 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('influxdb_processor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='influxdbprocessor',
            name='bucket',
            field=models.CharField(help_text='InfluxDB Bucket. Example: updates', max_length=256),
        ),
        migrations.AlterField(
            model_name='influxdbprocessor',
            name='org',
            field=models.CharField(help_text='InfluxDB organization. Example: homelab', max_length=256),
        ),
        migrations.AlterField(
            model_name='influxdbprocessor',
            name='timeout',
            field=models.IntegerField(default=10000, help_text='InfluxDB Bucket. Default: 10000'),
        ),
        migrations.AlterField(
            model_name='influxdbprocessor',
            name='token',
            field=models.CharField(help_text='InfluxDB Token.', max_length=256),
        ),
        migrations.AlterField(
            model_name='influxdbprocessor',
            name='url',
            field=models.CharField(help_text='InfluxDB URL. Example: http://x.x.x.x:8086/', max_length=256),
        ),
        migrations.AlterField(
            model_name='influxdbprocessor',
            name='verify_ssl',
            field=models.BooleanField(default=False, help_text='InfluxDB Bucket. Default: False'),
        ),
    ]
