# Generated by Django 5.1.3 on 2024-11-26 20:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Checker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checker_type', models.CharField(max_length=20)),
                ('checker_name', models.CharField(max_length=100)),
                ('schedule', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host_type', models.CharField(max_length=20)),
                ('host_name', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('active', 'Active'), ('stopped', 'Stopped'), ('failed', 'Failed')], default='active', max_length=20)),
                ('is_arhived', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Processor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('processor_type', models.CharField(max_length=20)),
                ('processor_name', models.CharField(max_length=100)),
                ('config', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_type', models.CharField(max_length=20)),
                ('provider_name', models.CharField(max_length=100)),
                ('config', models.JSONField()),
                ('schedule', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='HostChecker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.checker')),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.host')),
            ],
        ),
        migrations.AddField(
            model_name='host',
            name='checkers',
            field=models.ManyToManyField(through='core.HostChecker', to='core.checker'),
        ),
        migrations.CreateModel(
            name='Instance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instance_type', models.CharField(max_length=20)),
                ('instance_name', models.CharField(max_length=100)),
                ('is_update_available', models.BooleanField(default=False)),
                ('current_version', models.CharField(max_length=100)),
                ('new_version', models.CharField(max_length=100)),
                ('checker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.checker')),
            ],
        ),
        migrations.AddField(
            model_name='host',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.provider'),
        ),
    ]
