# Generated by Django 5.1.3 on 2024-11-28 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_provider_config_alter_provider_provider_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provider',
            name='provider_type',
            field=models.CharField(max_length=20),
        ),
    ]
