# Generated by Django 5.1.3 on 2024-11-29 14:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_is_arhived_host_is_archived'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='processor',
            name='config',
        ),
        migrations.AddField(
            model_name='instance',
            name='host',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.host'),
        ),
        migrations.AddField(
            model_name='processor',
            name='schedule',
            field=models.CharField(default='00 01 * * *', max_length=20),
        ),
        migrations.AlterField(
            model_name='instance',
            name='checker',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.checker'),
        ),
        migrations.CreateModel(
            name='CheckerProcessor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.checker')),
                ('processor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.processor')),
            ],
        ),
        migrations.AddField(
            model_name='checker',
            name='processors',
            field=models.ManyToManyField(through='core.CheckerProcessor', to='core.processor'),
        ),
        migrations.AddField(
            model_name='processor',
            name='checkers',
            field=models.ManyToManyField(through='core.CheckerProcessor', to='core.checker'),
        ),
    ]
