# Generated by Django 5.1.3 on 2024-11-30 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_processor_config_instance_host_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='instance',
            name='current_tag',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='instance',
            name='latest_version',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='instance',
            name='current_version',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='instance',
            name='new_version',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
