# Generated by Django 5.1.3 on 2024-11-30 23:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_instance_current_tag_instance_latest_version_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstanceProcessor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('processed', models.BooleanField(default=False)),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.instance')),
                ('processor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.processor')),
            ],
        ),
        migrations.AddField(
            model_name='instance',
            name='processors',
            field=models.ManyToManyField(through='core.InstanceProcessor', to='core.processor'),
        ),
        migrations.AddField(
            model_name='processor',
            name='instances',
            field=models.ManyToManyField(through='core.InstanceProcessor', to='core.instance'),
        ),
    ]
